---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  interval: 10m
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  install:
    createNamespace: true
  # https://artifacthub.io/packages/helm/metrics-server/metrics-server?modal=values
  values:
    args:
      - --kubelet-insecure-tls
