---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    # needed for daemonset/ingress-nginx-controller with hostNetwork=true
    pod-security.kubernetes.io/enforce: privileged
