---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      containers:
        - name: tailscale
          image: tailscale/tailscale:v1.96.5

          securityContext:
            privileged: true

          env:
            - name: TS_HOSTNAME
              value: homelab

            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth-key-secret
                  key: TS_AUTHKEY

            - name: TS_STATE_DIR
              value: /var/lib/tailscale

            - name: TS_EXTRA_ARGS
              value: "--advertise-routes=192.168.100.0/24"

            - name: TS_KUBE_SECRET
              value: ""

          volumeMounts:
            - name: state
              mountPath: /var/lib/tailscale
            - name: tun
              mountPath: /dev/net/tun

      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: tailscale-pvc
        - name: tun
          hostPath:
            path: /dev/net/tun
