---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-pvc
spec:
  storageClassName: local-path-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
