---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-bot-alert
  namespace: default
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
    namespace: '*'
  - kind: Kustomization
    name: '*'
    namespace: '*'
  providerRef:
    name: discord
