---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/gickup/
  - ../../base/home-assistant/
  - ../../base/homepage/
  - ../../base/jellyfin/
  - ../../base/linkding/
  # - ../../base/minecraft/
  - ../../base/opencode/
  - ../../base/obsidian-livesync/
  - ../../base/osrs-prices/
  - ../../base/tailscale/
  - ../../base/vaultwarden/
