---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/gickup/
  - ../../base/homepage/
  - ../../base/jellyfin/
  - ../../base/linkding/
  - ../../base/obsidian-livesync/
  - ../../base/osrs-prices/
  - ../../base/vaultwarden/
