---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/home-assistant/
  - ../../base/linkding/
  # - ../../base/minecraft/
  - ../../base/obsidian-livesync/
  - ../../base/opencode/
  - ../../base/osrs-prices/
  - ../../base/tailscale/
  - ../../base/todo/
  - ../../base/vaultwarden/
