---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: ghcr-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "oauth2",
                "password": "{{ .pat }}",
                "auth": "{{ printf "%s:%s" "oauth2" .pat | b64enc }}"
              }
            }
          }
  data:
    - secretKey: pat
      remoteRef:
        key: homelab-flux-github-token
