---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: homelab-flux-github-username
    - secretKey: password
      remoteRef:
        key: homelab-flux-github-token
