---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osrs-prices-webapp-runelite-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: osrs-prices-webapp-runelite-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: osrs-prices-webapp-runelite-pv
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - noserverino
    - dir_mode=0555
    - file_mode=0444
  csi:
    driver: smb.csi.k8s.io
    readOnly: true
    volumeHandle: "//syn.skwig.party#/#/Runelite_Bind"
    volumeAttributes:
      source: //syn.skwig.party/Runelite_Bind
      subDir: /
    nodeStageSecretRef:
      name: smb-share-credentials
      namespace: osrs-prices
