---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: osrs-prices
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/skwig/OsrsPrices/refs/heads/gh-pages/
  secretRef:
    name: github-credentials-secret
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: osrs-prices
spec:
  releaseName: osrs-prices
  targetNamespace: osrs-prices
  interval: 10m
  chart:
    spec:
      chart: osrsprices
      version: 1.0.0-c9d1c30
      sourceRef:
        kind: HelmRepository
        name: osrs-prices
  install:
    createNamespace: true
    remediation:
      retries: 1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 1
      remediateLastFailure: true
  # https://github.com/skwig/OsrsPrices/blob/master/charts/osrsprices/values.yaml
  values:
    webapp:
      imagePullSecrets:
        - name: ghcr-credentials-secret
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-production
          external-dns.alpha.kubernetes.io/hostname: osrs-prices.homelab.skwig.party
          external-dns.alpha.kubernetes.io/target: 192.168.100.47
        hosts:
          - host: osrs-prices.homelab.skwig.party
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: osrs-prices-homelab-tls
            hosts:
              - osrs-prices.homelab.skwig.party
      volumes:
        - name: app-data-flipping
          persistentVolumeClaim:
            claimName: osrs-prices-webapp-flipping-pvc
      volumeMounts:
        - name: app-data-flipping
          mountPath: /app-data/flipping-utilities/
      configMap:
        PriceArchiveApiOptions__BaseUri: http://osrs-prices-price-archive:8080
        FlippingUtilitiesOptions__DirectoryPath: /app-data/flipping-utilities/
    price-archive:
      imagePullSecrets:
        - name: ghcr-credentials-secret
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: osrs-prices-price-archive-projects-pvc
      volumeMounts:
        - name: app-data
          mountPath: /app-data/
      configMap:
        FileStorageOptions__BasePath: /app-data/
