---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: osrs-prices
spec:
  interval: 10m
  url: https://github.com/skwig/OsrsPrices
  ref:
    branch: master
  ignore: |
    /*
    !/charts/
  secretRef:
    name: github-credentials-secret
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: osrs-prices
spec:
  releaseName: osrs-prices
  targetNamespace: osrs-prices
  interval: 10m
  chart:
    spec:
      chart: ./charts/osrsprices
      version: 0.0.0
      sourceRef:
        kind: GitRepository
        name: osrs-prices
  install:
    createNamespace: true
  # https://github.com/skwig/OsrsPrices/blob/master/charts/osrsprices/values.yaml
  values:
    webapp:
      image:
        tag: master-11-8242d6217fb01185bc5633f0b915b01932f21edf
      imagePullSecrets:
        - name: ghcr-credentials-secret
      configMap:
        PriceArchiveApiOptions__BaseUri: http://price-archive
    price-archive:
      image:
        tag: master-11-8242d6217fb01185bc5633f0b915b01932f21edf
      imagePullSecrets:
        - name: ghcr-credentials-secret
