---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-lgtm
  labels:
    app: otel-lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-lgtm
  template:
    metadata:
      labels:
        app: otel-lgtm
    spec:
      containers:
        - name: otel-lgtm
          image: grafana/otel-lgtm:0.11.7
          imagePullPolicy: IfNotPresent
          ports:
            - { name: grafana,     containerPort: 3000 }  # Grafana UI
            # - { name: otlp-grpc,   containerPort: 4317 }  # OTel Collector gRPC
            # - { name: otlp-http,   containerPort: 4318 }  # OTel Collector HTTP
            - { name: loki,        containerPort: 3100 }  # Loki HTTP (+/otlp)
            - { name: tempo-http,  containerPort: 3200 }  # Tempo HTTP (query)
            - { name: mimir,       containerPort: 9009 }  # Mimir HTTP (+/otlp)
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
