---
apiVersion: v1
kind: Service
metadata:
  name: otel-lgtm
  labels:
    app: otel-lgtm
spec:
  type: ClusterIP
  selector:
    app: otel-lgtm
  ports:
    - { name: grafana,     port: 3000, targetPort: 3000 }
    # - { name: otlp-grpc,   port: 4317, targetPort: 4317 }
    # - { name: otlp-http,   port: 4318, targetPort: 4318 }
    - { name: loki,        port: 3100, targetPort: 3100 }
    - { name: tempo-http,  port: 3200, targetPort: 3200 }
    - { name: mimir,       port: 9009, targetPort: 9009 }
