---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smb-share-credentials
  namespace: csi-driver-smb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: smb-share-username
    - secretKey: password
      remoteRef:
        key: smb-share-password
