---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: syn-nidus-smb-retain
provisioner: smb.csi.k8s.io
parameters:
  source: //192.168.100.37/Test_Shared
  subDir: ${pvc.metadata.name}
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - guest
