---
creation_rules:
  # Talos secret files using SOPS
  - path_regex: talos/.*.sops.ya?ml
    encrypted_regex: '((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))'
    mac_only_encrypted: true
    azure_keyvault: https://skwig-homelab-kv-euw-prd.vault.azure.net/keys/sops/bda497ff566d4945ba8f5d1016483d29

stores:
  yaml:
    indent: 2
