---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-smb
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
spec:
  releaseName: csi-driver-smb
  targetNamespace: csi-driver-smb
  interval: 10m
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.17.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
  install:
    createNamespace: true
