services:
  versity:
    image: ghcr.io/versity/versitygw:v1.8.0
    container_name: versitygw
    restart: unless-stopped

    user: "1031:100"

    volumes:
      - /volume1/S3:/data/s3
      - /volume1/docker/versity/iam:/data/iam

    ports:
      - "7070:7070"

    environment:
      ROOT_ACCESS_KEY: ${VERSITY_ROOT_ACCESS_KEY}
      ROOT_SECRET_KEY: ${VERSITY_ROOT_SECRET_KEY}
      VGW_PORT: ":7070"
      VGW_ADMIN_PORT: ":7071"
      VGW_REGION: us-east-1
      VGW_BACKEND: posix
      VGW_BACKEND_ARG: /data/s3
      VGW_IAM_DIR: /data/iam
