---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: porkbun-webhook
spec:
  interval: 10m
  url: https://mdonoughe.github.io/porkbun-webhook
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
spec:
  releaseName: porkbun-webhook
  targetNamespace: cert-manager
  interval: 10m
  chart:
    spec:
      chart: porkbun-webhook
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: porkbun-webhook
        namespace: flux-system
  install:
    createNamespace: true
  values:
    groupName: acme.skwig.party
