---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors: {}
    exporters:
      otlphttp/tempo:
        endpoint: lgtm-stack-tempo-distributor.monitoring:3100
        tls:
          insecure: true
      otlphttp/loki:
        endpoint: http://lgtm-stack-loki-distributor.monitoring:3100/otlp
        tls:
          insecure: true
      otlphttp/mimir:
        endpoint: http://lgtm-stack-mimir-nginx.monitoring/otlp
        tls:
          insecure: true
      debug:
        verbosity: detailed
    extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679
    service:
      extensions:
        - health_check
        - pprof
        - zpages
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlphttp/tempo]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlphttp/mimir]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlphttp/loki]
