---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prometheus-stack
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 70.3.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  install:
    createNamespace: true
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    prometheus:
      enabled: true
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: smb-share-retain
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 10Gi
    alertManager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: smb-share-retain
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 1Gi
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-production
          external-dns.alpha.kubernetes.io/hostname: grafana.homelab.skwig.party
          external-dns.alpha.kubernetes.io/target: 192.168.100.47
        tls:
          - secretName: grafana-homelab-tls
            hosts:
              - grafana.homelab.skwig.party
        hosts:
          - grafana.homelab.skwig.party
        paths:
          - /

