---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/rancher/local-path-provisioner
  ref:
    tag: v0.0.31
  ignore: |
    /*
    !/deploy/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  releaseName: local-path-provisioner
  targetNamespace: local-path-provisioner
  interval: 10m
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner
      version: 0.0.31
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system
  install:
    createNamespace: true
  # https://github.com/rancher/local-path-provisioner/blob/master/deploy/chart/local-path-provisioner/values.yaml
  values:
    storageClass:
      name: local-path-retain
      reclaimPolicy: Retain
