---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus-stack
  labels:
    # needed for daemonset/kube-prometheus-stack-prometheus-node-exporter
    pod-security.kubernetes.io/enforce: privileged
