---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 76.5.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  dependsOn:
    - name: loki
    - name: tempo
  install:
    createNamespace: true
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    prometheus:
      enabled: true
      prometheusSpec:
        enableOTLPReceiver: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-share-retain
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 10Gi
    alertManager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-share-retain
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 1Gi
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-production
          external-dns.alpha.kubernetes.io/hostname: grafana.homelab.skwig.party
          external-dns.alpha.kubernetes.io/target: 192.168.100.47
        tls:
          - secretName: grafana-homelab-tls
            hosts:
              - grafana.homelab.skwig.party
        hosts:
          - grafana.homelab.skwig.party
        paths:
          - /
      additionalDataSources:
          # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
          - name: Loki
            uid: loki
            type: loki
            access: proxy
            url: http://loki.monitoring:3100
            isDefault: false
            jsonData:
              derivedFields:
                - name: "trace_id"
                  matcherType: "label"
                  matcherRegex: "trace_id"
                  url: "$${__value.raw}"
                  datasourceUid: "tempo"
                  urlDisplayLabel: "Trace: $${__value.raw}"
          # https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
          - name: Tempo
            uid: tempo
            type: tempo
            access: proxy
            url: http://tempo.monitoring:3200
            isDefault: false
            jsonData:
              tracesToLogsV2:
                customQuery: true
                datasourceUid: "loki"
                query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
                tags:
                  - key: "service.name"
                    value: "service_name"
              lokiSearch:
                datasourceUid: loki
              tracesToMetrics:
                datasourceUid: prometheus
              serviceMap:
                datasourceUid: prometheus


