---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alerts
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./infrastructure/controllers/alerts
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers-external-secrets
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./infrastructure/controllers/external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configs-external-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers-external-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./infrastructure/configs/external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
