---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alerts
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./infrastructure/alerts
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
