---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-helm
      version: 4.0.x
  interval: 1m0s
  values:
    adminUser:
      create: true
      passwordHash: $2y$10$EiaYvQ.I8IWtPqfQ3PxdreJaMERWoTjIe3uprLxR6OnWqjm.00WUi
      username: admin
    namespace: flux-system
    rbac:
      create: true
