---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  custom.js: ""
  custom.css: ""
  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: ""
  # https://github.com/homarr-labs/dashboard-icons
  services.yaml: |
    - Links:
      - OsrsPrices:
            href: https://osrs-prices.homelab.skwig.party
      - Vaultwarden:
            href: https://vaultwarden.skwig.party
            icon: vaultwarden.png
      - Linkding:
            href: https://linkding.homelab.skwig.party
            icon: linkding.png
      - Jellyfin:
            href: https://jellyfin.homelab.skwig.party
            icon: jellyfin.png
      - Grafana:
            href: https://grafana.homelab.skwig.party
            icon: grafana.png
      - Weave:
            href: https://weave.homelab.skwig.party
  settings.yaml: ""
  widgets.yaml: ""
