---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Links:
      - OsrsPrices:
            href: https://osrs-prices.homelab.skwig.party
      - Jellyfin:
            href: https://jellyfin.homelab.skwig.party
            icon: jellyfin.png
      - Grafana:
            href: https://grafana.homelab.skwig.party
            icon: grafana.png
      - Weave:
            href: https://weave.homelab.skwig.party
  widgets.yaml: ""
  docker.yaml: ""
