---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: couchdb
  namespace: flux-system
spec:
  interval: 10m
  url: https://apache.github.io/couchdb-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: couchdb
  namespace: flux-system
spec:
  releaseName: couchdb
  targetNamespace: couchdb
  interval: 10m
  chart:
    spec:
      chart: couchdb
      version: 4.6.1
      sourceRef:
        kind: HelmRepository
        name: couchdb
        namespace: flux-system
  install:
    createNamespace: true
