---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: grafana
# spec:
#   interval: 10m
#   url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-monolithic-tempo
spec:
  releaseName: lgtm-monolithic-tempo
  targetNamespace: monitoring
  interval: 10m
  chart:
    spec:
      chart: tempo
      version: 1.23.2
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  # https://artifacthub.io/packages/helm/grafana/tempo?modal=values
  values:
    persistence:
      enabled: true
      storageClassName: local-path-retain
      accessModes:
        - ReadWriteOnce
      size: 10Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-monolithic-loki
spec:
  releaseName: lgtm-monolithic-loki
  targetNamespace: monitoring
  interval: 10m
  chart:
    spec:
      chart: loki
      version: 6.35.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  # https://artifacthub.io/packages/helm/grafana/loki?modal=values
  values:
    loki:
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2025-08-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path-retain
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-monolithic-grafana
spec:
  releaseName: lgtm-monolithic-grafana
  targetNamespace: monitoring
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: grafana
  dependsOn:
    - name: lgtm-monolithic-tempo
    - name: lgtm-monolithic-loki
  install:
    createNamespace: true
  # https://artifacthub.io/packages/helm/grafana/grafana?modal=values
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-production
        external-dns.alpha.kubernetes.io/hostname: lgtm-monolithic.homelab.skwig.party
        external-dns.alpha.kubernetes.io/target: 192.168.100.47
      tls:
        - secretName: lgtm-monolithic-homelab-tls
          hosts:
            - lgtm-monolithic.homelab.skwig.party
      hosts:
        - lgtm-monolithic.homelab.skwig.party
    persistence:
      enabled: true
      storageClassName: local-path-retain
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
          - name: Loki
            uid: loki
            type: loki
            url: http://lgtm-monolithic-loki
            isDefault: false
          # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-data-source
          - name: Mimir
            uid: prom
            type: prometheus
            url: http://lgtm-monolithic-mimir/prometheus
            isDefault: true
          # https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
          - name: Tempo
            uid: tempo
            type: tempo
            url: http://lgtm-monolithic-tempo:3200
            isDefault: false
            jsonData:
              tracesToLogsV2:
                datasourceUid: loki
              lokiSearch:
                datasourceUid: loki
              tracesToMetrics:
                datasourceUid: prom
              serviceMap:
                datasourceUid: prom
