---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 10m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-monolithic-loki
spec:
  releaseName: lgtm-monolithic-loki
  targetNamespace: monitoring
  interval: 10m
  chart:
    spec:
      chart: loki
      version: 6.35.1
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  # https://artifacthub.io/packages/helm/grafana/loki?modal=values
  values:
    loki:
      storage:
        type: filesystem
        filesystem:
          admin_api_directory: null
      schemaConfig:
        configs:
          - from: "2025-08-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path-retain
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-monolithic-tempo
spec:
  releaseName: lgtm-monolithic-tempo
  targetNamespace: monitoring
  interval: 10m
  chart:
    spec:
      chart: tempo
      version: 1.23.2
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  # https://artifacthub.io/packages/helm/grafana/tempo?modal=values
  values:
    persistence:
      enabled: true
      storageClassName: local-path-retain
      accessModes:
        - ReadWriteOnce
      size: 10Gi
