---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:41.30
              args:
                - skwig/homelab
              envFrom:
                - secretRef:
                    name: renovate-token
                - configMapRef:
                    name: renovate-configmap
          restartPolicy: Never
