---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-token
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-github-token
