# yaml-language-server: $schema=https://raw.githubusercontent.com/cooperspencer/gickup/refs/heads/main/gickup_spec.json

source:
  github:
    - token: GITHUB_TOKEN
      exclude:
        - nixpkgs
        - Hyprland
        - aquamarine
      excludeorgs:
        - NixOS
      wiki: true
      issues: true
      gists: true
destination:
  local:
    - path: /gickup/backups
      structured: true

log:
  timeformat: 2006-01-02 15:04:05
