---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gickup
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: ghcr.io/cooperspencer/gickup:0.10.45
              args:
                - /gickup/conf/conf.yml
              envFrom:
                - secretRef:
                    name: gickup-github-token
              volumeMounts:
                - mountPath: /gickup/conf/
                  name: conf-yml
                - mountPath: /gickup/backups
                  name: backup
          volumes:
            - name: conf-yml
              configMap:
                name: gickup-conf-yml
            - name: backup
              persistentVolumeClaim:
                claimName: gickup-backup-pvc
          restartPolicy: Never
