apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gickup
resources:
  - namespace.yaml
  - gickup-cronjob.yaml
  - gickup-github-token-secret.yaml
  - s3.yaml

configMapGenerator:
  - name: gickup-conf-yml
    files:
      - conf.yml
