---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gickup-backup-pvc
spec:
  storageClassName: nfs-share-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
