---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: gickup-backup
spec:
  configuration:
    name: gickup-backup-configuration
  users:
    - name: gickup-minio-user-credentials
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: backup
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: nfs-share-retain
  buckets:
    - name: backup
      region: us-east-1
      objectLock: true
  requestAutoCert: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gickup-backup-configuration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gickup-backup-configuration
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.env: |-
          export MINIO_STORAGE_CLASS_STANDARD="EC:0"
          export MINIO_ROOT_USER="{{ .MINIO_ROOT_USER | toString }}"
          export MINIO_ROOT_PASSWORD="{{ .MINIO_ROOT_PASSWORD | toString }}"
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: minio-root-user
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: minio-root-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gickup-minio-user-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: CONSOLE_ACCESS_KEY
      remoteRef:
        key: minio-console-accesskey
    - secretKey: CONSOLE_SECRET_KEY
      remoteRef:
        key: minio-console-secretkey
