---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-configs
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/apps/overlays/production
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
