---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/monitoring/configs/overlays/production
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-configs
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/monitoring/controllers/overlays/production
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
