---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/monitoring/controllers/weave
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/monitoring/controllers/kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
