---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-cluster-secret-store
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://skwig-homelab-kv-euw-prd.vault.azure.net
      tenantId: b3033e23-4e79-48f8-a7b4-062fd451d4b2
      authSecretRef:
        clientId:
          name: azure-credentials
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-credentials
          key: ClientSecret
          namespace: external-secrets
