---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: todo-couchdb-app-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        username: todo
        password: "{{ .password | toString }}"
  data:
    - secretKey: password
      remoteRef:
        key: todo-couchdb-password
