apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo
resources:
  - namespace.yaml
  - release.yaml
  - github-credentials-secret.yaml
  - ghcr-credentials-secret.yaml
  - couchdb-release.yaml
  - couchdb-ingress.yaml
  - couchdb-admin-credentials-secret.yaml
  - couchdb-app-credentials-secret.yaml
  - couchdb-provision-cronjob.yaml
configMapGenerator:
  - name: todo-couchdb-provision-script
    files:
      - couchdb-provision.py
