---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  bootstrap:
    initdb: {}
  storage:
    size: 5Gi
    storageClass: local-path-retain
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: minio
      serverName: vaultwarden-db
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  monitoring:
    enablePodMonitor: true
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio
spec:
  configuration:
    destinationPath: s3://backup
    endpointURL: http://minio
    s3Credentials:
      accessKeyId:
        name: vaultwarden-minio-user-credentials
        key: CONSOLE_ACCESS_KEY
      secretAccessKey:
        name: vaultwarden-minio-user-credentials
        key: CONSOLE_SECRET_KEY
    wal:
      compression: bzip2
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwaren-db-backup
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  cluster:
    name: vaultwarden-db
  # method: plugin
  # pluginConfiguration:
  #   name: barman-cloud.cloudnative-pg.io
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: vaultwarden-backup
spec:
  configuration:
    name: vaultwarden-backup-configuration
  users:
    - name: vaultwarden-minio-user-credentials
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: backup
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: nfs-share-retain
  buckets:
    - name: backup
      region: us-east-1
      objectLock: true
  requestAutoCert: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-configuration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: vaultwarden-backup-configuration
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.env: |-
          export MINIO_STORAGE_CLASS_STANDARD="EC:0"
          export MINIO_ROOT_USER="{{ .MINIO_ROOT_USER | toString }}"
          export MINIO_ROOT_PASSWORD="{{ .MINIO_ROOT_PASSWORD | toString }}"
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: minio-root-user
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: minio-root-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-minio-user-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: CONSOLE_ACCESS_KEY
      remoteRef:
        key: minio-console-accesskey
    - secretKey: CONSOLE_SECRET_KEY
      remoteRef:
        key: minio-console-secretkey
