---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: porkbun-keys-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: api-key
      remoteRef:
        key: porkbun-api-key
    - secretKey: secret-key
      remoteRef:
        key: porkbun-secret-key
