---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
  namespace: busybox
spec:
  storageClassName: smb-share-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
