---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
  namespace: busybox
spec:
  storageClassName: syn-nidus-smb-retain
  volumeName: busybox
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
