---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: busybox
spec:
  volumes:
    - name: busybox-pvc
      persistentVolumeClaim:
        claimName: busybox-pvc
  containers:
    - name: busybox
      image: busybox:1.30.1
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 6000; done"
      volumeMounts:
        - mountPath: /storage
          name: busybox-pvc
