---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-minio
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m

  path: ./kubernetes/infrastructure/base/minio

  sourceRef:
    kind: GitRepository
    name: flux-system

  prune: true
  deletionPolicy: Orphan
  wait: true
