---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tempo
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-configs
    - name: infrastructure-monitoring-namespace

  interval: 1h
  retryInterval: 1m
  timeout: 5m

  path: ./kubernetes/monitoring/controllers/base/tempo

  sourceRef:
    kind: GitRepository
    name: flux-system

  prune: true
  deletionPolicy: Orphan
  wait: true
