---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  targetNamespace: external-dns
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    createNamespace: true
  values:
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/konnektr-io/external-dns-porkbun-webhook
          tag: v0.2.18
          pullPolicy: IfNotPresent
        args:
        - --domain-filter=skwig.party
        env:
        - name: GO_LOG
          value: "debug"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: porkbun-keys-secret
              key: api-key
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: porkbun-keys-secret
              key: secret-key
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
