---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-jellyfin
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-local-path-provisioner
    - name: infrastructure-csi-driver-smb
    - name: infrastructure-opentelemetry

  interval: 1h
  retryInterval: 1m
  timeout: 5m

  path: ./kubernetes/apps/base/jellyfin

  sourceRef:
    kind: GitRepository
    name: flux-system

  prune: true
  deletionPolicy: Orphan
  wait: true
