apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - namespace.yaml
  - qbittorrent-deployment.yaml
  - qbittorrent-ingress.yaml
  - qbittorrent-service.yaml
  - qbittorrent-pvc.yaml
