apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glauth
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: glauth
    includeTemplates: true
    includeSelectors: true

configMapGenerator:
  - name: glauth-config
    files:
      - config.cfg
