---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: glauth
spec:
  interval: 10m
  url: https://glauth.github.io/helm-glauth
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glauth
spec:
  releaseName: glauth
  targetNamespace: glauth
  interval: 10m
  chart:
    spec:
      chart: glauth
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: glauth
  install:
    createNamespace: true
  values:
    image:
      tag: v2.4.0
    config:
      storage:
        size: 1G
        class: local-path-retain
    backend:
      type: config
    database:
      shell: false
    service:
      type: ClusterIP
      ports:
       - name: ldap
         internal: 3893
         external: 3893
       - name: ldaps
         internal: 3894
         external: 3894
       - name: web
         internal: 5555
         external: 5555
    ingress:
      enabled: false
