---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-standard-trixie
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
  storage:
    size: 20Gi
    storageClass: local-path-retain
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  monitoring:
    enablePodMonitor: true
