---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 6h
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.13.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  releaseName: immich
  targetNamespace: immich
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: immich
  # https://artifacthub.io/packages/helm/immich/immich?modal=values
  values:
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library-pvc
    server:
      controllers:
        main:
          containers:
            main:
              env:
                DB_HOSTNAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db-app
                      key: host
                DB_PORT:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db-app
                      key: port
                DB_DATABASE_NAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db-app
                      key: dbname
                DB_USERNAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db-app
                      key: username
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db-app
                      key: password
                DB_VECTOR_EXTENSION: pgvector
      persistence:
        external-library:
          type: persistentVolumeClaim
          existingClaim: immich-external-library-pvc
          globalMounts:
            # Configure Immich external libraries from subdirectories such as
            # /external/immich-bind/user1, /external/immich-bind/user2, etc.
            - path: /external/immich-bind
              readOnly: true
      ingress:
        main:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-production
            external-dns.alpha.kubernetes.io/hostname: immich.skwig.party
            external-dns.alpha.kubernetes.io/target: 192.168.100.47
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: immich.skwig.party
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
          tls:
            - secretName: immich-tls
              hosts:
                - immich.skwig.party
    machine-learning:
      persistence:
        cache:
          enabled: true
          type: persistentVolumeClaim
          size: 10Gi
          accessMode: ReadWriteOnce
          storageClass: local-path-retain
    valkey:
      enabled: true
      persistence:
        data:
          enabled: true
          type: persistentVolumeClaim
          size: 1Gi
          accessMode: ReadWriteOnce
          storageClass: local-path-retain
