---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-credentials-secret
  namespace: obsidian-livesync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: adminUsername
      remoteRef:
        key: obsidian-livesync-admin-username
    - secretKey: adminPassword
      remoteRef:
        key: obsidian-livesync-admin-password
