apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: OPENCODE_SERVER_PASSWORD
      remoteRef:
        key: opencode-server-password
