---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  bootstrap:
    initdb: {}
  storage:
    size: 1Gi
    storageClass: local-path-retain
  backup:
    barmanObjectStore:
      destinationPath: s3://backup
      endpointURL: http://minio
      s3Credentials:
        accessKeyId:
          name: linkding-minio-user-credentials
          key: CONSOLE_ACCESS_KEY
        secretAccessKey:
          name: linkding-minio-user-credentials
          key: CONSOLE_SECRET_KEY
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: linkding-db-backup
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  cluster:
    name: linkding-db
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: linkding-backup
spec:
  configuration:
    name: linkding-backup-configuration
  users:
    - name: linkding-minio-user-credentials
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: backup
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: nfs-share-retain
  buckets:
    - name: backup
      region: us-east-1
      objectLock: true
  requestAutoCert: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-backup-configuration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: linkding-backup-configuration
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.env: |-
          export MINIO_STORAGE_CLASS_STANDARD="EC:0"
          export MINIO_ROOT_USER="{{ .MINIO_ROOT_USER | toString }}"
          export MINIO_ROOT_PASSWORD="{{ .MINIO_ROOT_PASSWORD | toString }}"
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: minio-root-user
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: minio-root-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-minio-user-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: CONSOLE_ACCESS_KEY
      remoteRef:
        key: minio-console-accesskey
    - secretKey: CONSOLE_SECRET_KEY
      remoteRef:
        key: minio-console-secretkey
