---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
  storage:
    size: 1Gi
    storageClass: local-path-retain
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  monitoring:
    enablePodMonitor: true

