---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials-secret
spec:
  target:
    name: db-credentials-secret
  data:
    - secretKey: LD_DB_HOST
      remoteRef:
        key: linkding-db-app
        property: host
    - secretKey: LD_DB_PORT
      remoteRef:
        key: linkding-db-app
        property: port
    - secretKey: LD_DB_DATABASE
      remoteRef:
        key: linkding-db-app
        property: dbname
    - secretKey: LD_DB_USER
      remoteRef:
        key: linkding-db-app
        property: username
    - secretKey: LD_DB_PASSWORD
      remoteRef:
        key: linkding-db-app
        property: password
