---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linkding
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linkding
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
        - name: linkding
          image: "ghcr.io/sissbruecker/linkding:1.41.0-plus-alpine"
          imagePullPolicy: Always
          envFrom:
            # - configMapRef:
            #     name: linkding-configmap
            - secretRef:
                name: superuser-credentials-secret
          env:
            - name: LD_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: linkding-db-app
                  key: host
            - name: LD_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: linkding-db-app
                  key: port
            - name: LD_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: linkding-db-app
                  key: dbname
            - name: LD_DB_USER
              valueFrom:
                secretKeyRef:
                  name: linkding-db-app
                  key: username
            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-db-app
                  key: password
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/linkding/data
              name: linkding-data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-pvc
