---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superuser-credentials-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: LD_SUPERUSER_NAME
      remoteRef:
        key: linkding-superuser-username
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: linkding-superuser-password
