---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ww-gitops
spec:
  targetNamespace: weave
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      createSecret: false
      username: admin
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-production
        external-dns.alpha.kubernetes.io/hostname: weave.homelab.skwig.party
        external-dns.alpha.kubernetes.io/target: 192.168.100.47
      tls:
        - secretName: weave-homelab-tls
          hosts:
            - weave.homelab.skwig.party
      hosts:
        - host: weave.homelab.skwig.party
          paths:
            - path: /
              pathType: ImplementationSpecific
